### ISSUE TITLE
Content does not fit on the screen in mobile view

### ISSUE THREAD

**Issue by ayyilmaz** [Inoryum-Ltd/aesto#10]
Content does not fit on the screen in mobile view. The contents under the class = "it-content it-canvas" class continue to stretch towards the right of the screen. Not responsive.

for testing mobile view: https://ready.mobi/

tested url: https://istihbarat.club/blog/bahai-lotus-tapinagi/

![cvvdere](https://user-images.githubusercontent.com/24845098/103479810-470dd000-4de1-11eb-9995-79ac315263f5.png)

**Comment by saleheenkhan** [comment]
Thanks for reporting the issue..

This will be fixed on next release
