### ISSUE TITLE
Youtube video overflows other content

### ISSUE THREAD

**Issue by ayyilmaz** [Inoryum-Ltd/aesto#9]
Youtube video overflows other content. I put divider after video embed but it doesnot enough video overflows on text.

You can test on this link: https://istihbarat.club/blog/bahai-lotus-tapinagi/

![vvv](https://user-images.githubusercontent.com/24845098/103464080-47a35980-4d42-11eb-8aa1-5b71b828cf34.png)

**Comment by ayyilmaz** [comment]
I solved my problem by adding these lines to code injection.
```
    .fluid-width-video-wrapper iframe, .fluid-width-video-wrapper object, .fluid-width-video-wrapper embed {
        position: relative !important; 
    }
    
    .fluid-width-video-wrapper {
     	padding: 5px !important;   
    }
```

**Comment by saleheenkhan** [comment]
Hi,
I am glad you fixed the issue.. I will patch the theme with your fix

Thanks
